apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: MOODLE_USERNAME
          valueFrom:
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_USERNAME
        - name: MOODLE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_PASSWORD
        - name: MOODLE_SITE_NAME
          value: "Learning Management System"
        - name: MOODLE_DATABASE_TYPE
          value: "mariadb"
        - name: MOODLE_DATABASE_HOST
          value: "mariadb"
        - name: MOODLE_DATABASE_NAME
          value: "bitnami_moodle"
        - name: MOODLE_DATABASE_USER
          secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_USER
        - name: MOODLE_DATABASE_PASSWORD
          secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_PASSWORD
        - name: MOODLE_DATABASE_PORT_NUMBER
          value: "3306"
        - name: APACHE_HTTPS_PORT_NUMBER
          value: "443"
        - name: APACHE_HTTP_PORT_NUMBER
          value: "80"
        - name: BITNAMI_DEBUG
          value: "false"
        - name: MOODLE_SKIP_BOOTSTRAP
          value: "no"
        
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        resources:
          requests:
            memory: "556Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: MARIADB_DATABASE
          value: "bitnami_moodle"
        - name: MARIADB_USER
          secretKeyRef:
              name: mariadb-secret
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          secretKeyRef:
              name: mariadb-secret
              key: MARIADB_PASSWORD
        - name: MARIADB_ROOT_PASSWORD
          secretKeyRef:
              name: mariadb-secret
              key: MARIADB_ROOT_PASSWORD
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc

