apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: bitnami/moodle:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: MOODLE_DATABASE_TYPE
              value: "mysqli"
            - name: MOODLE_DATABASE_HOST
              value: "mariadb"
            - name: MOODLE_DATABASE_NAME
              value: "bitnami_moodle"
            - name: MOODLE_DATABASE_USER
              value: "moodle"
            - name: MOODLE_DATABASE_PASSWORD
              value: "moodle"
          volumeMounts:
            - name: moodle-data
              mountPath: /bitnami/moodle
      volumes:
        - name: moodle-data
          persistentVolumeClaim:
            claimName: moodle-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          resources:
            requests:
              memory: "556Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "bitnami_moodle"
            - name: MYSQL_USER
              value: "moodle"
            - name: MYSQL_PASSWORD
              value: "moodle"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc

