apiVersion: v1
kind: Secret
metadata:
  namespace: feat-rayhan
  name: moodle-secret
type: Opaque
data:
  MOODLE_USERNAME: YWRtaW4=
  MOODLE_PASSWORD: bW9vZGxl
  MOODLE_DATABASE_USER: bW9vZGxl
  MOODLE_DATABASE_PASSWORD: bW9vZGxl
---
apiVersion: v1
kind: Secret
metadata:
  namespace: feat-rayhan
  name: mariadb-secret
type: Opaque
data:
  MARIADB_USER: bW9vZGxl
  MARIADB_PASSWORD: bW9vZGxl
  MARIADB_ROOT_PASSWORD: bW9vZGxl