apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  clusterIP: None


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: moodle
  name: moodle
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moodle
  type: LoadBalancer
status:
  loadBalancer: {}
